version = 1

[[annotations]]
path = [
  "**/package.json",
  "CHANGELOG.md",
  "**/.gitignore",
  "docs/CNAME",
  ".husky/**",
  "**/package-lock.json",
  "**/pnpm-lock.yaml",
  "**/.prettierrc",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 hexaTune LLC"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [".github/ISSUE_TEMPLATE/**", ".github/PULL_REQUEST_TEMPLATE.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 hexaTune LLC"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["hexawebshare/src/components/assets/**","hexawebshare/static/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 hexaTune LLC"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**/*.d.ts"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 hexaTune LLC"
SPDX-License-Identifier = "MIT"
