# SPDX-FileCopyrightText: 2025 hexaTune LLC
# SPDX-License-Identifier: MIT

name: Auto add issues and PRs to hTuneSys Project 16

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    name: Add add project (hexaWebShare)
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/hTuneSys/projects/16
          github-token: ${{ secrets.ORG_PROJECT_TOKEN }}
