# SPDX-FileCopyrightText: 2025 hexaTune LLC
# SPDX-License-Identifier: MIT

name: üè∑Ô∏è Check Semantic PR Title

on:
  pull_request:
    branches:
      - develop
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-title:
    name: Validate PR title (hexaWebShare)
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            refactor
            test
            docs
            ci
            perf
            build
            main
            hotfix
            style
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
