# SPDX-FileCopyrightText: 2025 hexaTune LLC
# SPDX-License-Identifier: MIT

name: ðŸ“„ REUSE Compliance

on: [pull_request]

jobs:
  reuse:
    name: REUSE Compliance (hexaWebShare)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pip install reuse
      - run: reuse lint
